a= int(input("Enter The First number:"))
b= int(input("Enter The Second number"))
add= str(a+b)
sub= str(a-b)
multi= str(a*b)
div= str(a/b)
print("Addition: "+ add)
print("Subtraction: " +sub)
print("Multiplocation: "+ multi)
print("Division: "+ div)
